### ISSUE TITLE
Identify potential variables

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#1]
E. Coli readings
- E. Coli beach readings from two days ago
- E. Coli beach readings from previous day

[Beach Water readings](https://data.cityofchicago.org/Parks-Recreation/Beach-Water-Quality-Automated-Sensors/qmqz-2xku)
- Solar radiation
- Water temperature
- Turbidity
- Wave height
- Wave period

[Beach Weather Stations](https://data.cityofchicago.org/Parks-Recreation/Beach-Weather-Stations-Automated-Sensors/k7hf-8y75)
- Air temperature
- Rain intensity
- Rain interval
- Wind

Nearby Actions
- Open locks
- [Park events](https://data.cityofchicago.org/Events/Chicago-Park-District-Event-Permits/pk66-w54g)
  Calendar-based data
- Day of week
- Holidays
- Forecasted _e. coli_ from current model

**Comment by ChrisProkop** [comment]
Ideas for variables and data processing:
- Indicator for beach direction (North/South)
  - Indicators for other location categorizations (~4/5/6/7 clusters of locations).  The GBM kind of picks up on this I think, but we need to be fair to the GLM or save the GBM time.
  - Change of previous day from its previous day (Day-1 - Day-2).  
  - Change of previous day from its two days prior (Day-1 - Day-3).
  - etc.

**Comment by tomschenkjr** [comment]
Please record ideas for feature creation on the [Potential Features wiki page](https://github.com/Chicago/e-coli-beach-predictions/wiki/Potential-features)
