### ISSUE TITLE
Organize Code

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#107]
Organize the code into clear sections to make the following steps easier and more flexible

1. Data collection and cleaning
2. Data preprocessing for modelling, such as filtering and subsetting
3. Feature engineering
4. Data mining
5. Predictor selection
6. Modelling
7. ROC and PR Curve Production
8. Confusion Matrix Production

**Comment by nicklucius** [comment]
Placeholder for cleaning/organization issues that we need to address:
- [x] remove 2016 USGS prediction errors (there are multiple days with large negative E. Coli levels)
- [x] `Client.ID` has 1984 NAs out of 26823 records (due to missing data in portal)
- [x] Remove outlier readings in `Reading.2`
- [x] Remove beach reading observations from the year 1916
- [x] Fix lock reading data errors - too many NAs
- [x] Convert weather time variables
- [x] Create two datasets to reduce NAs (one with water sensor and USGS data, one without)
- [x] Look into missing `Sample.Collection.Time` data
- [x] add day of year
- [x] add weekday code
- [x] Field names have changed -- cannot have variables starting with a number (will not work with Random Forests)
- [x] DNA mean is listed as a geomean, but is it really geomean or is it arithmetic mean
- [x] check that every date during the season has a row (no rows for 7/8/2006, 7/6/2006, or 7/9/2006)
- [x] add function for creating columns with priorday.1, priorday.2, etc. (e.g. see ```shift_previous_data()``` at line ```444``` [here](https://github.com/nicklucius/e-coli-beach-predictions/blob/master/analysis.R#L444)).

**Comment by nicklucius** [comment]
The nickDev branch now has most of the data merged together (except weather).

@CallinOsborn is importing the CSVs that have weather from 2006 - 2015

I am getting new 2016 daily and hourly weather from Dark Sky / forecast.io.

**Comment by nicklucius** [comment]
@CallinOsborn I went through and double-checked the Lats/Longs in the `cleanbeachnames.csv` file. Row `98` and `99` look like the coordinates for Rainbow instead of Rogers.

![image](https://cloud.githubusercontent.com/assets/16853555/20268777/350a0eb6-aa46-11e6-981c-0497dedd9d96.png)

Do you know if this error is in the original CSV, or only in the new one?

**Comment by CallinOsborn** [comment]
@nicklucius you are exactly right, good catch. The actual latlong of Rogers should be 42.0213,-87.6666. I just uploaded the new `cleanbeachnames.csv` with the corrected Rogers Beach LatLong.

**Comment by CallinOsborn** [comment]
I don't know how big of a problem this will be long term, but we do have multiple readings for some beaches on the same day.  As evidenced here with Albion beach:

![image](https://cloud.githubusercontent.com/assets/20862662/20313868/e5a22cc2-ab1d-11e6-9504-77d8f981be87.png)

A couple thoughts I had, are keep the highest `Mean` from the same beach on that day and use that.  Or we can somehow try and find an average of all the beaches and use that as the reading.

**Comment by nicklucius** [comment]
@CallinOsborn - Is that due to the beach name mapping? If multiple beaches map to Albion, then each of those beaches becomes an Albion reading for that day.

Related: #67, #22, #61

**Comment by CallinOsborn** [comment]
That is exactly what it is.  For example on May 23, 2006 here were the samples:

![capture](https://cloud.githubusercontent.com/assets/20862662/20315622/420d1c82-ab24-11e6-953e-fde0a835796b.PNG)

The Columbia, Hartigan, and Leone readings all map back to Albion, creating the 3 readings for Albion Beach in one day. This happens consistently in years past.

**Comment by CallinOsborn** [comment]
@nicklucius  Here's an example of the vast difference of a geomean at a 'beach' in the duplicates 
![image](https://cloud.githubusercontent.com/assets/20862662/20718651/047449ee-b61f-11e6-8c6f-efc0bcc24942.png)
As you can see at the Jarvis predictions are pretty close together (51.2, 30.6),but the Leone Beach predictions (55.9, 2419.6) are not even in the same ballpark as each other.
