### ISSUE TITLE
USGS Prediction change from 2015 - 2016

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#113]
Are the beaches used for the 2015 USGS predictions different than the 2016 USGS predictions? 

Is [this code](https://github.com/Chicago/e-coli-beach-predictions/blob/master/11_USGSpredictions.R#L38-L43
) removing real 2015 USGS predictions, or just duplicated predictions?

**Comment by CallinOsborn** [comment]
We don't know exactly which beaches they were predicting and then extrapolating from. But the following are the groups of beaches beaches for drek in 2015:

```
1- Osterman
2- Oak Street/North Ave
3- Howard/Rogers/Albion/Juneway/Leone/Jarvis
4- Foster
5- 31st/South Shore/57th/63rd/39th
6- Ohio/12th
7- Montrose
8- Rainbow
9- Calumet
```

There were 9 predicting beaches in 2016, which correspond to 1 predicting beach in 2015, so I just used the same beaches that were predicted for in 2016 to use as the reference table for 2015.

**Comment by nicklucius** [comment]
Thank you!
