### ISSUE TITLE
Duplicate rows in Water Data

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#114]
The [code ](https://github.com/Chicago/e-coli-beach-predictions/blob/master/15_WaterQuality.R#L36-L37)in `15_WaterQuality.R` says it is cleaning out duplicates, but when I manually tested the code, it did not remove any rows.

**Comment by CallinOsborn** [comment]
I just ran the code again manually, I didn't get any duplicates.  It might have just been the day that I ran it that R was being a little finicky.  I would say keep that line of code in there, we don't lose a lot of time leaving it in, and it is a double check to make sure that there are no duplicated rows when it comes in.

**Comment by nicklucius** [comment]
Sounds good.
