### ISSUE TITLE
Lock Data

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#116]
It looks like the reason we have so many NAs (referenced [here](https://github.com/Chicago/e-coli-beach-predictions/issues/107#issuecomment-258452930)) is because there are only rows of data in the dataframe `lock_data` for dates on which at least one lock is open. So if all locks were closed on a given day, we do not have a row for that day.

We need to fill in all the NAs with 0s as appropriate for lock data.

**Comment by CallinOsborn** [comment]
This is taken care of with pull request #120 .
