### ISSUE TITLE
Use one naming convention

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#117]
Pick a naming convention (e.g. camelCase, underscore_case) and use it consistently.

**Comment by geneorama** [comment]
Don't forget about the possibility of using the dot as a space as in `read.socrata`.  Personally I think the dot can make sense in function names in packages, like `read.socrata`, but should be avoided for variables. However, it's worth mentioning.

**Comment by tomschenkjr** [comment]
Is this still open for consideration? Is some code rewriting still needed?

**Comment by nicklucius** [comment]
I think this issue is outdated, since the code has been reworked. We never did settle on one convention, but  now it's more important to clean up the modelling functions for readability. I had been holding off on the cleanup, because doing that will set me up nicely for documenting the project.

**Comment by nicklucius** [comment]
Closed by #141.
