### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#130]
Per the discussion with @CallinOsborn and @nicklucius - should we change the name of this repo to "clear-water"?

**Comment by nicklucius** [comment]
I like it so yes for me. It looks like I don't have permissions to change the name.

**Comment by tomschenkjr** [comment]
Changed. https://github.com/Chicago/clear-water

Your pushes should auto-forward to the new url. But, as a best practice, should update the "origin" on your remote with the following:

```shell
git remote set-url origin https://github.com/Chicago/clear-water.git
```

**Comment by tomschenkjr** [comment]
Seems to be going well, so am closing.
