### ISSUE TITLE
CONTRIBUTING.md file

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#133]
@tomschenkjr - While working on the README.md file, I've been thinking about whether to create a CONTRIBUTING.md file too. I see there are a few different versions for Chicago projects. Is there a good template I can adopt, or should I create one specific for this project?

**Comment by tomschenkjr** [comment]
For the context of this, seems like the food inspection project is the best one as the template since it gives instructions on cross validating and submitting model improvements (https://github.com/Chicago/food-inspections-evaluation/blob/master/CONTRIBUTING.md).

**Comment by nicklucius** [comment]
I'm writing up ```CONTRIBUTING.md``` and I see that there is a CLA in the template, but we don't have a CLA set up for Clear Water. I'm looking at how to set it up, and I have a copy of the RSocrata CLA since I've signed it.

I have to choose which of the following to require. I can set this up--any thoughts? 

"Choose any extra fields to require on your agreement:
* Email
* Name
* Mailing address
* Country
* Phone or Skype
* Type "I AGREE" 
* Type your initials
* Corporate Contributor Information "

**Comment by tomschenkjr** [comment]
Actually, I’ll have to do this bit. Because of permissions, we use an account “cityofchicago” to create the CLA. Only the creator of the CLA can later modify it. We use the central account so we can modify it later. Assign this to  me.

**Comment by tomschenkjr** [comment]
Contributing License Agreement has been created for clear-water https://www.clahub.com/agreements/Chicago/clear-water

I've also created one for clear-water-app https://www.clahub.com/agreements/Chicago/clear-water-app
