### ISSUE TITLE
Finalize Design

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#137]
The design will need to integrate the interactive Shiny app.

**Comment by tomschenkjr** [comment]
I've created a new branch `issue137` that contains the redesigned website. I need to tweak some things and will open a pull request against `gh-pages` for you to review. 

If you checkout that branch, you can just open the `index.html` file to preview the new site.

**Comment by tomschenkjr** [comment]
As a note to myself for work:

### Visible index.html
- [x] Add Nick's introductory paragraph (and figure out how we want to display that)
- [x] Need to fix whatever issue is preventing `chart.js` from loading properly
- [x] Add final website link to the sharing button links
- [x] Upgrade to FontAwesome 4.7 so the thermometer displays next to "weather"

### index.html code
- [x] In the `meta` tags, need to place where the URL will be
- [x] Need to place preview image to be used in social media sharing previews (e.g., twitter cards) - _partially done, need to place permanent URL in `<meta>` tags_

### Prettify
- [x] Create a CSS entry to support the `<iframe>` that will display the Shiny app

**Comment by nicklucius** [comment]
This looks great. I completed the pull request. 

The shiny app has been updated on the EC2 server so that the "build a model" page is the whole app. I also cleaned it up and changed the graph and formatting.

**Comment by tomschenkjr** [comment]
I reassigned this to me since the remaining tasks are basically mine.

**Comment by nicklucius** [comment]
@tomschenkjr - Here's what I found out on the ```chart.js``` issue. It looks like the [contents](https://github.com/Chicago/clear-water/blob/gh-pages/assets/js/chart.js) of ```assets/js/chart.js``` is the html source for the GitHub page containing ```chart.js```, so maybe something must have happened during the porting? 

That is not the only issue, though. Once I fix that, I get this error:

```chart.js: ReferenceError: $ is not defined```

I think this is solved by moving these from the bottom to the top of the body of ```index.html```

```
		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>
			<script src="https://code.highcharts.com/highcharts.js"></script>
    		<script src="https://code.highcharts.com/modules/exporting.js"></script>
```
Now I no longer get any errors. But I still cannot get ```chart.js``` to load.

**Comment by tomschenkjr** [comment]
Is this on a local test? I’m not seeing the changes on the `gh-pages` branch

**Comment by nicklucius** [comment]
Yes, it's a local test. I'll push to gh-pages so you can see.

**Comment by nicklucius** [comment]
I fixed it - the chart is showing up now.

**Comment by tomschenkjr** [comment]
That was an amazing effective `git push` command, then.

**Comment by nicklucius** [comment]
`git push` is the new restart. But really, I just tried modified the `div` and it did the trick.
