### ISSUE TITLE
Link to Beach Swim Advisories - data is not updated

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#143]
There is a button that links to Beach Swim Advisories. CPD has not updated this dataset since the end 2016, most likely because they are issuing advisories using the Lab data now, instead of the USGS model predictions.

We could add a link to this map, which is blank until around noon when the daily predictions are generated: 

https://data.cityofchicago.org/Parks-Recreation/Clear-Water-Map/mf7j-mc8j

**Comment by tomschenkjr** [comment]
Ah ok. Yeah, a link to the map would be interesting as well. I just threw in some links to give an idea of what the content could be in that area, so open to ideas.

We can also have a standalone page that embeds the advisories map as well.

**Comment by tomschenkjr** [comment]
@nicklucius - is this ok or do we need to do a bit more with it?

**Comment by nicklucius** [comment]
@tomschenkjr - I just pushed a commit that changed the link to the predictions map.
