### ISSUE TITLE
Clean-up "challenge" page

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#145]
Need to clean-up the challenge page a bit. Below are some tasks and the point-of-contact. Check them off once they are finished. 

  - [x] Fix the link to "home" on the submenu - @tomschenkjr
  - [x] Fix the `<iframe>` to limit the scrolling (especially vertically) - @tomschenkjr
  - [x] Remove the "For contact information" footer in the Shiny app. Let's use more standard language of "&copy; 2017 <names> and licensed under <license>" (btw, what is the home repo for the app?) - @nicklucius 
  - [x] Fix the social navigation icons in the footer - @tomschenkjr
  - [x] Add narrative preceding the app so people know what to do - @nicklucius 
  - [ ] Add City Seal to header/nav - @tomschenkjr

This could potentially have a lot of merge conflicts. Just ping this thread when you start work and I'll hold-off so we don't spend all day fixing the conflicts.

**Comment by nicklucius** [comment]
@tomschenkjr - Sounds good. The home repo for the Shiny App is https://github.com/rchesak/Chicago-Beaches. I wanted to ask for thoughts on storing my tweaks. Right now they are only on the EC2 server. Maybe fork the project to our GitHub?

**Comment by tomschenkjr** [comment]
Yes, let’s fork it over to Chicago. Be sure to keep the original licensing since it’s required of the MIT license.

**Comment by tomschenkjr** [comment]
I've created a branch, `issue145` for this. I'm beginning work on it so you may not want to touch anything on this issue, yet.

**Comment by nicklucius** [comment]
Sounds good, I'll hold off. But I did complete the Shiny app license language task, since it's a different repo.

**Comment by tomschenkjr** [comment]
@nicklucius - thanks on the Shiny app. Actually, can you just link to the MIT license (in our repo) in the text instead of the full thing?

**Comment by nicklucius** [comment]
Sure thing, will do.

**Comment by tomschenkjr** [comment]
@nicklucius - thanks, looks great.

I've pushed changes back to `issue145` branch. When you get a chance, you can add your bits. I'm done working on it for a moment.

**Comment by nicklucius** [comment]
Left out the issue # in my commit message: https://github.com/Chicago/clear-water/commit/28af49f9c4a8c97303c0f499070729e7ac529a83

**Comment by tomschenkjr** [comment]
Looked at the nav bar on the challenge page and realized it may not make sense to include the seal since the nav does not follow along the page. Closing this issue for now.
