### ISSUE TITLE
Remove "View License" 

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#146]
Right now, the "view license" doesn't work well because it attempts to open the link within the `iframe`.

Meanwhile, I've updated that webpage so it contains the necessary copyright, attribution, and license information so it's not needed on the app.

![image](https://user-images.githubusercontent.com/1639121/29085040-87ba5ae8-7c33-11e7-97ea-634161d551a5.png)

**Comment by nicklucius** [comment]
Completed via https://github.com/Chicago/Chicago-Beaches/commit/c7a54d2edc94dc0cf68b7f0339fcc8852baf1ddd

**Comment by tomschenkjr** [comment]
Hrm, I didn’t know you could reference commits with Org/Repo@commit. Neat!
