### ISSUE TITLE
Create a train/test split for benchmarking

### ISSUE THREAD

**Issue by ntdef** [Chicago/e-coli-beach-predictions#15]
It would probably be nice to get a training and test dataset split for comparing new models, similar to the way Kaggle selects a winning model. One thing we'll have to look out for is making sure the training and testing datasets are balanced w.r.t  the number of positives and negatives.

**Comment by tomschenkjr** [comment]
For conversation in an upcoming meeting:

We've split the data into [test/train](https://github.com/Chicago/e-coli-beach-predictions/blob/master/analysis.R#L109-L113) using traditional methods. But given the limited time where we have both predictions and actual observations, should we use more nuanced methods like k-fold?

**Comment by kbrose** [comment]
I think k-fold cross validation is the way to go. I think a good target for this issue would be a function that takes in the data-frame and breaks it up into train/test sets.

Do we want to rely on purely random sampling, or do we want to explicitly sample within beaches and within years?

**Comment by kbrose** [comment]
After seeing large performance swings in the GBM model based on how the train/test split was done, this question deserves a closer look.

Perhaps it would be best to preserve 2015 (most recent year) as a more final testing set and only use the data from pre-2015 for now. It would still make sense to do "out-of-range" train/test splits, e.g. doing a leave-one-year-out-cross-validation.

**Comment by tomschenkjr** [comment]
_Train_ period: 2006 - 2014
_Test_ period (e.g., use random seeding / _k_-fold methods): 2006 - 2014
_Validation_: 2015 (leave out, fit predictions from 2006-2014 to 2015 actual observations)

**Comment by kbrose** [comment]
Definitely need to do leave-one-year-out cross validation.

Blue line is performance on testing set with random 70% train, 30% test, red line is performance when leaving the year 2010 out (leaving other years out performs similarly). Notice that the blue line is significantly higher than the red line, indicating better performance. Doing a random split of train/test over-estimates performance significantly, thus, out-of-time sampling (e.g. leave-one-year-out CV) should be employed.

![roc](https://cloud.githubusercontent.com/assets/4053170/13626703/f1e9ef6a-e589-11e5-95f5-04e940c6a984.png)

![pr](https://cloud.githubusercontent.com/assets/4053170/13626705/f4a7c92a-e589-11e5-9c7d-12243f2ae6be.png)

**Comment by kbrose** [comment]
(Reproduce plots by running `python gbm.py` inside the `python_src` directory of commit [81480174357c8a5caec651eec4d43a0686224bf8](https://github.com/kbrose/e-coli-beach-predictions/commit/81480174357c8a5caec651eec4d43a0686224bf8) (comparing train/test split methods) in my fork.
