### ISSUE TITLE
Remove ">" from data

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#17]
When the test results are the highest levels (2420), the data contains a ">" and needs to be removed.

**Comment by fgregg** [comment]
I'm not sure we should fully remove it. If we get sophisticated enough we can model that censoring and it should improve our predictions.

I would recommend keeping it in the data, and handling it in the analysis code.

**Comment by tomschenkjr** [comment]
I think the >2420 is a bit of an automated insertion whenever the cap is met. So, 2420 implies "2420 or greater". Mostly, was just needing to remove it because it's causing data-type issues and can't perform numeric operations on it.

Agree on the censoring though.

Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org

**Comment by fgregg** [comment]
I think we should keep it in the data and have it be handled by analysis
code.

If you want do it in the data, I would recommend turning them into NAs, and
adding a new column called "Reasong Missing" that indicated right censoring.

On Thu, Dec 3, 2015 at 12:21 PM, Tom Schenk Jr notifications@github.com
wrote:

> I think the >2420 is a bit of an automated insertion whenever the cap is
> met. So, 2420 implies "2420 or greater". Mostly, was just needing to remove
> it because it's causing data-type issues and can't perform numeric
> operations on it.
> 
> Agree on the censoring though.
> 
> Tom Schenk Jr.
> 
> Chief Data Officer
> 
> Department of Innovation and Technology
> 
> City of Chicago
> 
> (312) 744-2770
> 
> tom.schenk@cityofchicago.org
> 
> data.cityofchicago.org
> 
> ---
> 
> From: Forest Gregg notifications@github.com
> Sent: Thursday, December 3, 2015 12:17 PM
> To: Chicago/e-coli-beach-predictions
> Cc: Schenk, Tom
> Subject: Re: [e-coli-beach-predictions] Remove ">" from data (#17)
> 
> I'm not sure we should fully remove it. If we get sophisticated enough we
> can model that censoring and it should improve our predictions.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/Chicago/e-coli-beach-predictions/issues/17#issuecomment-161736890
> 
> > .
> 
> [https://avatars3.githubusercontent.com/u/1639121?v=3&s=400]<
> https://github.com/Chicago/e-coli-beach-predictions/issues/17#issuecomment-161736890
> 
> 
> Remove ">" from data · Issue #17 · Chicago/e-coli-beach-predictions
> When the test results are the highest levels (2420), the data contains a
> ">" and needs to be removed.
> Read more...<
> https://github.com/Chicago/e-coli-beach-predictions/issues/17#issuecomment-161736890
> 
> 
> ---
> 
> This e-mail, and any attachments thereto, is intended only for use by the
> addressee(s) named herein and may contain legally privileged and/or
> confidential information. If you are not the intended recipient of this
> e-mail (or the person responsible for delivering this document to the
> intended recipient), you are hereby notified that any dissemination,
> distribution, printing or copying of this e-mail, and any attachment
> thereto, is strictly prohibited. If you have received this e-mail in error,
> please respond to the individual sending the message, and permanently
> delete the original and any copy of any e-mail and printout thereof.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Chicago/e-coli-beach-predictions/issues/17#issuecomment-161738009
> .

## 

773.888.2718
