### ISSUE TITLE
Normalize the name of beaches

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#22]

**Comment by tomschenkjr** [comment]
There are 60+ names of beaches, but the actual number of beaches is smaller. Need to combine the various spellings into single observations. Use cpdbeaches.com to help normalize the names

**Comment by IrvicRodriguez** [comment]
I created a dictionary in Python for the beaches. I noticed the R script also has commented lines filtering into the 'Client.ID' as did the Python Script on Thursday.

**Comment by IrvicRodriguez** [comment]
Also, since we are using the R script for the project. I would need to handle off my Python script to a team mate for them to implement or learn how to do similar in R. Whichever comes first.

**Comment by mattesweeney** [comment]
@IrvicRodriguez -- can you make a pull request?

**Comment by tomschenkjr** [comment]
Per #30, need to double-check the names of beaches and if the mapping is correct.
