### ISSUE TITLE
DEFINEDNAME repeated

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#32]
When running the data-cleaning code, the following message gets repeated quite a bit. Is this something that can be prevented?

`DEFINEDNAME: 20 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 07 3b 00 00 00 00 ff ff 00 00 00 00`

This message specifically happens for some of the calls to `split_sheets`. Specifically, it happens with

`df2006 <- split_sheets("data/ChicagoParkDistrict/raw/Standard 18 hr Testing/2006 Lab Results.xls", 2006)`

**Comment by tomschenkjr** [comment]
It's a known bug https://github.com/hadley/readxl/issues/82 from the package that's reading the Excel files. I'm not sure we can suppress it on our side and may just need to wait for the fix.

Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org
