### ISSUE TITLE
Are beaches systematically sampled?

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#39]
The beach readings also report the time-of-day when they were taken. Is there a systematic difference in the sampling time for beaches (e.g., does the sampler always go from the north side to the south side?)

**Comment by kbrose** [comment]
It looks there is, in fact, some moderate systematic sampling. I hope to get more conclusive data, but for now these plots show that beaches tend to be sampled in a similar order.

The y-axis here shows time-of-day as a fraction (i.e. 0.25 = 6:00 AM, 0.50 = 12:00 PM).

This is 2015:
![2015_sampling_times](https://cloud.githubusercontent.com/assets/4053170/12836136/b29aa67e-cb7b-11e5-98aa-b15e03749a69.png)

and 2014:
![2014_sampling_times](https://cloud.githubusercontent.com/assets/4053170/12836175/fc9be81e-cb7b-11e5-8c4b-423bfe55c061.png)

Over-all histograms:
![sampling_time_hists](https://cloud.githubusercontent.com/assets/4053170/12836200/310b5c6a-cb7c-11e5-8baf-4183cb0fe982.png)

I'll be uploading the code to create these plots soon.

**Comment by kbrose** [comment]
And probably more usefully, reading time vs. E coli level (E. coli on log scale):
![sample_collection_vs_e_coli](https://cloud.githubusercontent.com/assets/4053170/12838307/234becbe-cb92-11e5-8186-e213b04a9a96.png)

**Comment by kbrose** [comment]
I'm going to go ahead and conclude that there's not a meaningful bias being introduced by the systematic sampling. Correlations below.

```
Pearson correlation : -0.0999245374366
Spearman correlation: -0.110404169309
```

I'll close this issue out with a PR that contains the code to reproduce the results here.

**Comment by fgregg** [comment]
These correlations are dominated by the vast majority of measurements that
are in the normal range. Might be worth splitting the measurements into a
high, low groups (on the e-coli warning threshold) and then do a
statistical test on those two groups to see if later, presumably hotter
beaches are more likely to have above-threshold readings.

**Comment by kbrose** [comment]
Good point. Do you think a simple t-test would make sense here?

Comparing **below threshold** to **above threshold** results in a t-statistic of 8.55 (indicating the below threshold readings have a _higher_ mean) with a p-value in the range of `1.3e-17`. The actual difference in means is 9:28 AM for below threshold samples and 9:07 AM for above threshold samples.

The QQ plot shows a very slight bias towards sampling later for above-threshold readings in low quantiles, then a very slight bias towards sampling later for below-threshold readings in all other quantiles (also note that only 840 of 15390 samples occur after 0.50 (noon), and only 78 of 15390 samples occur after 0.55 (1:12 PM), so those large deviations in quantiles after 0.50 are probably just noise):

![qq_plot](https://cloud.githubusercontent.com/assets/4053170/12851343/f8fbd6f6-cbee-11e5-8822-df8040ebe17c.png)

**Comment by fgregg** [comment]
Yeah a t-test should be fine. Interesting results!

On Fri, Feb 5, 2016 at 10:16 AM, Kevin Rose notifications@github.com
wrote:

> Good point. Do you think a simple t-test would make sense here?
> 
> Comparing _below threshold_ to _above threshold_ results in a t-statistic
> of 8.55 (indicating the below threshold readings have a _higher_ mean)
> with a p-value in the range of 1.3e-17. The actual difference in means is
> 9:28 AM for below threshold samples and 9:07 AM for above threshold samples.
> 
> The QQ plot shows a very slight bias towards sampling later for
> above-threshold readings in low quantiles, then a very slight bias towards
> sampling later for below-threshold readings in all other quantiles (also
> note that only 840 of 15390 samples occur after 0.50 (noon), and only 78 of
> 15390 samples occur after 0.55 (1:12 PM), so those large deviations in
> quantiles after 0.50 are probably just noise):
> 
> [image: qq_plot]
> https://cloud.githubusercontent.com/assets/4053170/12851343/f8fbd6f6-cbee-11e5-8822-df8040ebe17c.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Chicago/e-coli-beach-predictions/issues/39#issuecomment-180425522
> .

## 

773.888.2718

**Comment by kbrose** [comment]
Went ahead and re-ran the t-test separately for each beach. The fact that beaches _are_ systematically sampled would mean that the extremely significant results could be misleading: it could be due to the fact that some beaches do tend to have more E. coli than others, and those beaches tend to be sampled later/earlier. Recall that positive values indicate the below-threshold E. coli readings occurred before the above-threshold E. coli readings and vice versa.

```
tests comparing below threshold to above threshold:
    OVERALL:
    t-statistic: 8.55127346702
    p-value    : 1.33063091657e-17
    below thresh mean: 0.394764367671 (9:28)
    below thresh mean: 0.379836057149 (9:06)
    Calumet
        t-statistic: 1.72467025159
        p-value    : 0.0849790485826
    Rainbow
        t-statistic: 1.36394878544
        p-value    : 0.172995064038
    South Shore
        t-statistic: -0.759367131722
        p-value    : 0.447877101683
    63rd Street
        t-statistic: 1.26822208041
        p-value    : 0.205112706683
    57th Street
        t-statistic: 1.82456762704
        p-value    : 0.0684737802227
    Margaret T Burroughs
        t-statistic: 2.4186906637
        p-value    : 0.0158180966479
    12th Street
        t-statistic: -0.0792431645494
        p-value    : 0.936861078889
    Ohio Street
        t-statistic: 1.4554272177
        p-value    : 0.145975678624
    Oak Street
        t-statistic: 3.5288039152
        p-value    : 0.000443963126158
    North Avenue
        t-statistic: 3.82107887666
        p-value    : 0.000144445648852
    Montrose
        t-statistic: 1.12559764231
        p-value    : 0.260689330672
    Foster
        t-statistic: 1.9102247243
        p-value    : 0.0565040661337
    Osterman
        t-statistic: -0.0498791351824
        p-value    : 0.96023281201
    Lane
        t-statistic: -0.404926510214
        p-value    : 0.685852155884
    Hartigan
        t-statistic: 3.18546832016
        p-value    : 0.00151144693849
    North Shore
        t-statistic: 2.20203048062
        p-value    : 0.0285087905509
    Columbia
        t-statistic: 0.42771126117
        p-value    : 0.66920228346
    Leone
        t-statistic: 0.125416637427
        p-value    : 0.90024655748
    Marion Mahoney Griffin
        t-statistic: 1.57552455553
        p-value    : 0.115603955834
    Howard
        t-statistic: 1.93327328582
        p-value    : 0.053627970931
    Rogers
        t-statistic: 2.02641673566
        p-value    : 0.0431201227206
    Juneway
        t-statistic: 2.60510744407
        p-value    : 0.00939085830226
    Loyola
        t-statistic: -0.331816926689
        p-value    : 0.740320749349
    Fargo
        t-statistic: 0.580224773942
        p-value    : 0.567659005273
    Oakwood
        t-statistic: 1.98512911354
        p-value    : 0.0476520252729
    Montrose Dog
        t-statistic: 0.586080017494
        p-value    : 0.558191058171
```

Correcting for multiple hypotheses using an `alpha` of 0.05 ([https://en.wikipedia.org/wiki/Multiple_comparisons_problem#What_can_be_done](https://en.wikipedia.org/wiki/Multiple_comparisons_problem#What_can_be_done)) results in an `alpha'` of 0.00197 ([http://www.wolframalpha.com/input/?i=1-(1-.05)%5E(1%2F26)](http://www.wolframalpha.com/input/?i=1-%281-.05%29%5E%281%2F26%29)) and shows that only Oak Street, North Avenue, and Hartigan are "statistically significant", each one of which with a positive t-statistic. Not quite sure what to make of this information. It's possible that the slight auto-correlation present in the beach samplings is resulting in under-estimates of the p-values, and that all of these values are in fact not capable of rejecting the null hypothesis with the desired confidence.

**Comment by kbrose** [comment]
(didn't mean to close, clicked the "close and comment" instead of "comment")

**Comment by kbrose** [comment]
Run `python data_investigations.py` to recreate (most) of these figures.
