### ISSUE TITLE
"Shift" data to prior day or previous observations

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#47]
The data is currently organized so each row represents a lab test result at a beach on a given day. The remainder of the row then shows all of the information associated with that day.

However, to look at the impact of previous weather and other variables from prior days, need to organize the data set to make it easier to run analysis against historical data.

**Comment by beckeroobonsai** [comment]
This is accomplished in python with code committed in issue #55

**Comment by tomschenkjr** [comment]
The Python code has been merged. 

Anyone want to take-up R?

**Comment by tomschenkjr** [comment]
Sorry, I just saw @nicklucius did this for R. We're all good, so closing the issue.
