### ISSUE TITLE
forecast weather data for days without reading

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#58]
Even for days where E. coli readings were not taken (e.g., most weekend days), it is still possible to get the weather data. This data should be downloaded and added to the data-set so that models that rely on the previous day's weather can be better informed.

**Comment by mmcneill** [comment]
Working on this now.  Do we only care about making sure each reading has weather data for the one previous day or should I pull a more complete set of weather data for all summer month / beach combinations in our time interval?

**Comment by kbrose** [comment]
Let's do the more complete set just to be sure -- maybe the weather 2 or 3 days ago could be just as important as the weather from 1 day ago. In pseudo-code, I'd say

```
for each year:
    for each beach:
        mn = first day where there is an E. coli reading
        mx = last day where there is an E. coli reading
        for each day from (mn - N) to mx:
            get weather data for beach and day
```

where `N` is some reasonable number (probably 3).

**Comment by mmcneill** [comment]
Okay great, thanks.  I submitted a pull request last night that should close this issue, but if someone who was trying to do a model based on previous days' weather could check to make sure it looks correct that would be great.  I only had to pull 784 more day/beach combos based on the pseudo code above.
