### ISSUE TITLE
Improve the read-in function Python code to generalize "lag" data

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#60]
There are a couple of options on reading-in data, such as the definition of "lag". Namely, whether lag means "previous reading" or "previous date"

**Comment by kbrose** [comment]
The function has been slightly improved (e.g. vectorized) in #64. I believe the current method (where lag refers to previous date) is the right solution. Since there will be `NaN` values, most notably on a lot of weekend dates, the real issue now becomes dealing with `NaN` values: #65.

**Comment by ChrisProkop** [comment]
If weekend dates are only taken in some circumstances, and those circumstances are for any other reason than randomness, then we shouldn't include them at all in the model.  I think people were saying on Tuesday that Saturday was only recorded if Friday was bad?  

Lag variables and rolling averages should be built off of only Monday-Friday if that is the case.
