### ISSUE TITLE
Shorten the name of beaches

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#61]
Per @beckeroobonsai, should shorten the name of beaches to a single word or something more manageable within R/Python.

**Comment by kbrose** [comment]
Need to rename columns of `cleanbeachnames.csv` to something that will be less confusing for new-comers. Current names are `old`, `new`, and `short`. The group decided that the names should be changed to `old`, `interim`, and `target`.
