### ISSUE TITLE
Filling in NaN values

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#65]
How should `NaN` values be filled in (if at all)?

Using the city-wide mean for a given day might not be appropriate for filling in `NaN`s on the weekends, since the beaches that are sampled on the weekend are only sampled because they had a high reading on Friday (and maybe on Thursday? -- don't know the exact resampling rule) possibly causing bias in those readings.

Using a moving average could similarly be biased if the weekend samples are not excluded from the moving average.

**Comment by kbrose** [comment]
@ChrisProkop mentions filling a missing value with

`city_mean + average difference between city mean and current beach reading`

**Comment by tomschenkjr** [comment]
City mean at which time? Summer mean?

Or could look at reading at beach, regress on the mean reading for that beach based on the day of the summer, day of week, and weather. Especially fitting for a multi-level model.

Also, for those looking to do some new work, can look at multiple imputation https://cran.r-project.org/web/packages/Amelia/vignettes/amelia.pdf
