### ISSUE TITLE
Look at missing data

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#73]
Look at:
- Missing `Reading.1`
- Missing `Reading.2`
- Missing `e.coli levels`

**Comment by kbrose** [comment]
Need to investigate possibly missing weather data as well.

**Comment by mattesweeney** [comment]
Looked into the forecast.io weather data and found 578 missing rows. For each range of dates by year and beach, I identified missing dates with the code below.  Snapshots show some output, and you can see that most missing dates are in May -- especially May 13th and May 17th for some reason -- and in 2006.

``` r
library(dplyr)
b.dates=as.data.frame(beach_readings %>% group_by(Client.ID, Year) %>% summarise(min_date = min(Full_date), max_date = max(Full_date)))
Client.ID=""
missing_date=""
missingdf=data.frame(missing_date, Client.ID)
class(missingdf$missing_date)="Date"
for (i in 1:nrow(b.dates)){
      daterange <- seq(b.dates[i,3], b.dates[i,4], by = 1)
      b=as.data.frame(daterange[!daterange %in% beach_readings[which(beach_readings$Client.ID == b.dates[i,1] & b.dates[i,2]), "Full_date"]])
      if(nrow(b)==0){next}
      b$Client.ID=b.dates[i,1]
      colnames(b) = c("missing_date", "Client.ID")
      b$missing_date=as.character(b$missing_date)
      missingdf=rbind(missingdf,b)
}

missingdf=as.data.frame(missingdf)
missingdf=missingdf[-1,]
missingdf$missing_date=as.Date(missingdf$missing_date)
missingdf$Year <- as.numeric(format(missingdf$missing_date, "%Y"))
missingdf$Month <- format(missingdf$missing_date,"%B")
missingdf$Weekday <- weekdays(missingdf$missing_date)
missingdf$Date <- format(missingdf$missing_date,"%m %d")
as.data.frame(missingdf %>% group_by(Client.ID) %>% summarise(n_missing_dates=n()))
as.data.frame(table(missingdf$Year))
as.data.frame(table(missingdf$Date))
as.data.frame(table(missingdf$Month))
as.data.frame(table(missingdf$Weekday))
as.data.frame(table(missingdf$missing_date))
```

![screen shot 2016-04-13 at 12 55 47 am](https://cloud.githubusercontent.com/assets/11640123/14484018/7f82346a-0112-11e6-95ed-56bf7fa17329.png)

![screen shot 2016-04-13 at 12 55 15 am](https://cloud.githubusercontent.com/assets/11640123/14484021/83fdcbb2-0112-11e6-8513-5333e7f32d82.png)

![screen shot 2016-04-13 at 12 56 23 am](https://cloud.githubusercontent.com/assets/11640123/14484025/9776d21a-0112-11e6-8a53-0871fde6d4a5.png)
