### ISSUE TITLE
2007

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#86]
The year 2007 appears to be an outlier. Do we know why?

It looks like 17% of beach-days in 2007 were above the threshold, the only other year to break 10% was 2006 at 10.83%. The average E. coli reading was 218, with the next highest being 154 (again in 2006):

``` python
>>> import read_data as rd
>>> df = rd.read_data()
>>> df['year'] = df['Full_date'].map(lambda x: x.year)
>>> df = df[['year', 'Escherichia.coli']]
>>> df['decision'] = df['Escherichia.coli'] > 235.0
>>> df.groupby(by='year').mean()
      Escherichia.coli  decision
year
2006        153.538675  0.108295
2007        218.194024  0.172055
2008        123.900806  0.080582
2009        152.893786  0.092134
2010        143.637305  0.082264
2011        123.185564  0.073419
2012        127.129486  0.075764
2013        143.362148  0.075367
2014        141.687537  0.082411
2015        127.839362  0.085680
```

Notably, it appears as if **_not**_ including 2007 in the training set for any other year improves performance:

Using 2007 in all training sets except the one estimating 2007:
![roc_using_2007](https://cloud.githubusercontent.com/assets/4053170/14224363/3768f78e-f85e-11e5-9cad-5042c776be28.png)

Not using 2007 in any training set:
![roc_not_using_2007](https://cloud.githubusercontent.com/assets/4053170/14224365/447be508-f85e-11e5-82ab-4ba7fdee16ff.png)

(Run `python modeling.py` using commit d451c6e5099bc43f2899b70e9577760b7c25aae5 to reproduce, you will need to manually comment out the part that uses `& is_not_2007` on line 54 in `modeling.py` to see performance when 2007 is included.)

**Comment by tomschenkjr** [comment]
I'll ping Parks department to see if anything was different in 2007. I looked at high-level weather trends--as a potential cause--and 2007 did not stand out.

**Comment by kbrose** [comment]
It looks like removing 2006 cleans it up further (but curiously, also makes it perform worse at FPRs > 0.6). Which makes me now remember that someone might have said something about some sort of policy changing in 2008...?

I have not thoroughly investigated how removing each year individually effects the estimates, so it's possible that removing more years from the training set is actually just a regularization method and is stopping some overfitting.

Removing 2006 and 2007 from _all_ training sets, same model as above:

![roc](https://cloud.githubusercontent.com/assets/4053170/14251829/5d6ba998-fa4a-11e5-8b9a-d15f03660b44.png)

**Comment by tomschenkjr** [comment]
@kbrose - Hrm, I don't remember any policy change for 2008.
