### ISSUE TITLE
"time" related variables in forecastio are in absolute UNIX time

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#88]
Variables such as `sunriseTime` and time-of-max-temperature-occurence are not relative to the day, but in absolute UNIX time. We probably want to process these variables to be relative to the day they are describing.

**Comment by ZombieSocrates** [comment]
What I ended up doing is re-expressing each UNIX time as a float value that's basically "the number of hours after the prior midnight."  So if the sun rose at 5:20 am, the value of `sunriseTime` would be 5.333

You can take the UNIX `sunriseTime` in seconds, subtract away the seconds  equivalent of the `Full_date`, and then subtract 5 hours from that (to account for the conversion between GMT and Central Time).  To that effect...

```
df.sunriseTime = [round(float(val.components[1] + val.components[2]*1.0/60 + val.components[3]*1.0/3600),4) for val in pd.to_datetime(df.sunriseTime, unit = 's') - pd.Timedelta(hours = 5) - pd.to_datetime(df.Full_date)]
```

All the val.components[index] stuff just leaves the hours as hours and converts the minutes and seconds to hours by dividing by 60 and 3600, respectively.  No guarantee that this is the prettiest/fastest code, but it seems to work.

I implemented this in a for loop as a post-processing step after running `read_data` on all of the time related variables.  If you feel it's worth pushing to `read_data.py`, I'd be happy to give it a shot.

**Comment by kbrose** [comment]
Thanks for taking this on! A Pull Request would be great! If you want any help with that, don't hesitate to ask.

Looking at the rest of the `read_data.py`, it seems like it might make the most sense to create a short function that does the post-processing and call that inside the relevant if statement (i.e. the `if read_daily_forecast:` clause). Honestly, though, it's a pretty big file that, while not terribly messy, is not terribly clean either, so whatever makes the most sense to you/seems the cleanest is probably for the best.

**Comment by ZombieSocrates** [comment]
Sure, I can wrap the above into a helper function and then call it on any column with 'Time' in the name.  Feel free to consider this "assigned" to me.

One caveat: I'm leaving for a business trip tomorrow, so I won't be at the meeting.  I'll try to submit the request over the course of the week, but at the very latest expect it over the weekend if my schedule gets away from me.
