### ISSUE TITLE
Start simple model

### ISSUE THREAD

**Issue by fgregg** [Chicago/e-coli-beach-predictions#9]
- [ ] Autogressive with
- [x] Day of week
- [ ] Holiday
- [x] Beach
- [x] Their forecast levels
- [ ] Levels in other beaches

**Comment by tomschenkjr** [comment]
@mncneil is working on this, using a naive model where "today's" prediction is dependent on yesterdays readings. Incorporating elements of #37 by using `Reading.1` and `Reading.2` in the model

**Comment by tomschenkjr** [comment]
Precision-recall graphs for some simple models:
- black-solid = naive model (prevoius geomean); 
- black-dashed = naive model (previous high reading); 
- blue = previous geomean + icon (summary of day weather); 
- red = previous geomean + day of week + month; 
- green = previous geomean + icon + day of week + month + client.id (beach)
  ![pasted image at 2016_02_07 03_40 pm](https://cloud.githubusercontent.com/assets/1639121/12937250/5ac4ae8c-cf6c-11e5-96c5-35aa57bfb951.png)
