### ISSUE TITLE
Include information from other beaches

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#90]
(A subset of #62)

The modelling code as of PR #89 does not include any information from other beaches, e.g. a single row in the data frame only includes information about the beach it describes. We should include information from other beaches, perhaps reporting the mean value of different variables (such as E. coli) per group from @ChrisProkop's beach groupings.

**Comment by ChrisProkop** [comment]
Prior mean per group seems best.  I think doing the previous for every other beach adds a lot that a GBM or RF or GLM won't really be able to use effectively.
